### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by humminghorse** [GuildWorks/titech-2020#4]
## HTML, CSS, Javascript
- [x] 教材作成

## Vue(Nuxt)
- [x] 会員登録ページ作成
(- [ ] 初回パスワード変更ページ) 後回し
- [x] ログインページ作成
- [x] プロフィールページ作成
- [x] プロフィール編集ページ作成
- [x] メンバーリストで自分を選んだら、 /profile に遷移させたい
- [x] 教材作成
- [x] メニューの表示制御
    - [x] ログイン前: ログイン、ユーザー登録
    - [x] ログイン後: メンバーリスト、あなたのプロフィール
- [x] [ログイン前ならログインページにリダイレクトさせる](https://github.com/GuildWorks/titech-2020/issues/4#issuecomment-702690295)

以下、余裕があれば
- [ ] ユーザー登録ページとログインページをカッコよくしたい
- [ ] スタイル指定をtailwindに直す?
- [ ] フッターの場所を固定したい

## Firebase
Firebase authでユーザー登録、ログイン、ログアウト
Firebase storeでプロフィール登録、メンバーリスト取得、メンバープロフィール取得、マイプロフィール取得、マイプロフィール編集
- [x] セットアップ
- [x] ユーザー登録
       参考: https://github.com/GuildWorks/titech-firebase-auth-sample
- [x] ログイン
- [x] ログアウト
- [x] プロフィール登録 [ユーザー登録処理の中でuser.profileを(detailは空で)作成](https://github.com/GuildWorks/titech-2020/pull/9)
  - [x] アイコンアップロード?(マイプロフィール編集の中かも)
- [x] メンバーリスト取得
- [x] メンバープロフィール取得
- [x] マイプロフィール取得(できたら)
- [x] マイプロフィール編集(できたら)
- [ ] 教材作成

### メモ
- 自分のプロフィール画面は、3日目のFirebaseの日に含める
- 複数ユーザーの表示をローカルで確認したい人には、メールアドレスを複数用意してもらうか、周りの人に自分のローカルでユーザー登録してもらう
- 講義の中で写経してもらうのは、メンバー一覧とメンバー詳細にする
- それ以外の画面は、参考として、pullして見てもらう(コンポーネント分割も参考として見てもらうだけにする)        

## 資料作成
- [ ] 英語化

**Comment by humminghorse** [comment]
Firestore参考
https://dev.classmethod.jp/articles/firebase-cloud-firestore-ios/

**Comment by humminghorse** [comment]
一通りの機能は作れた。
## 第3回残作業
- [ ] 講義で編集してもらうプロジェクト(スタート地点のコード)を用意する
- [ ] 資料づくり
- [ ] 資料の英語化

## 余裕があればやりたい
- エラー解消(possibly undefined的なやつがたくさん出ている)
